# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    module = bld.create_ns3_module('ddsa', ['lq-olsr', 'ami'])
    module.source = [
        'model/util/dap.cc',
        'model/meters/rp/ddsa-routing-protocol-base.cc',
        'model/meters/rp/global-retrans-ddsa-routing-protocol-base.cc',
        'model/meters/rp/individual-retrans-ddsa-routing-protocol-base.cc',
        'model/meters/rp/original-ddsa-routing-protocol.cc',
        'model/meters/rp/dumb-ddsa-routing-protocol.cc',
        'model/meters/rp/dynamic-retrans-ddsa-routing-protocol.cc',
        'model/meters/rp/flooding-ddsa-routing-protocol.cc',
        'model/meters/l3prot/global-retrans-ddsa-ipv4-l3-protocol.cc',
        'model/meters/l3prot/individual-retrans-ddsa-ipv4-l3-protocol.cc',
        'model/meters/l3prot/ddsa-ipv4-l3-protocol-base.cc',
        'model/daps/rp/malicious-dap-routing-protocol.cc',
        'model/daps/l3prot/failing-ipv4-l3-protocol.cc',
        'helper/ddsa-helper.cc',
        'helper/ddsa-internet-stack-helper.cc',
        ]

    module_test = bld.create_ns3_module_test_library('ddsa')
    module_test.source = [
        'test/ddsa-test-suite.cc',
        ]

    headers = bld(features='ns3header')
    headers.module = 'ddsa'
    headers.source = [
        'model/util/dap.h',
        'model/meters/rp/ddsa-routing-protocol-base.h',
        'model/meters/rp/global-retrans-ddsa-routing-protocol-base.h',
        'model/meters/rp/individual-retrans-ddsa-routing-protocol-base.h',
        'model/meters/rp/original-ddsa-routing-protocol.h',
        'model/meters/rp/dumb-ddsa-routing-protocol.h',
        'model/meters/rp/dynamic-retrans-ddsa-routing-protocol.h',
        'model/meters/rp/flooding-ddsa-routing-protocol.h',
		'model/meters/l3prot/ddsa-ipv4-l3-protocol-base.h',
        'model/meters/l3prot/global-retrans-ddsa-ipv4-l3-protocol.h',
        'model/meters/l3prot/individual-retrans-ddsa-ipv4-l3-protocol.h',
        'model/daps/rp/malicious-dap-routing-protocol.h',
        'model/daps/l3prot/failing-ipv4-l3-protocol.h',
        'helper/ddsa-helper.h',
        'helper/ddsa-internet-stack-helper.h',
        ]

    if bld.env.ENABLE_EXAMPLES:
        bld.recurse('examples')

    # bld.ns3_python_bindings()

