# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    module = bld.create_ns3_module('ddsa', ['lq-olsr'])
    module.source = [
        'model/ddsa-routing-protocol-adapter.cc',
        'model/ipv4-l3-protocol-ddsa-adapter.cc',
        'helper/ddsa-helper.cc',
        'helper/ddsa-internet-stack-helper.cc',
        ]

    module_test = bld.create_ns3_module_test_library('ddsa')
    module_test.source = [
        'test/ddsa-test-suite.cc',
        ]

    headers = bld(features='ns3header')
    headers.module = 'ddsa'
    headers.source = [
        'model/ddsa-routing-protocol-adapter.h',
        'model/ipv4-l3-protocol-ddsa-adapter.h',
        'helper/ddsa-helper.h',
        'helper/ddsa-internet-stack-helper.h',
        ]

    if bld.env.ENABLE_EXAMPLES:
        bld.recurse('examples')

    # bld.ns3_python_bindings()

