def build(bld):
    module = bld.create_ns3_module('ami', ['network'])
    module.source = [
        'model/simple-header.cc',
        'helper/ami-helper.cc',
        ]

    module_test = bld.create_ns3_module_test_library('ami')
    module_test.source = [
        'test/ami-test-suite.cc',
        ]

    headers = bld(features='ns3header')
    headers.module = 'ami'
    headers.source = [
        'model/simple-header.h',
        'helper/ami-helper.h',
        ]

    if bld.env.ENABLE_EXAMPLES:
        bld.recurse('examples')

